DROP TABLE OTHERS;

CREATE TABLE OTHERS (
	OTHER_INT INT NULL ,
	OTHER_LONG NUMBER NULL ,
	OTHER_BIT SMALLINT DEFAULT 0 NOT NULL,
	OTHER_STRING VARCHAR2(32) NOT NULL
)
NOLOGGING 
NOCACHE 
NOPARALLEL;

INSERT INTO OTHERS VALUES(1, 8888888, 0, 'Oui');
INSERT INTO OTHERS VALUES(2, 9999999999, 1, 'Non');